CREATE TABLE user_account (
    id BIGINT NOT NULL AUTO_INCREMENT,
    open_id VARCHAR(64) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    nickname VARCHAR(40) NOT NULL,
    avatar_url VARCHAR(500) NULL,
    city_code VARCHAR(20) NULL,
    city_name VARCHAR(40) NULL,
    bio VARCHAR(160) NULL,
    interest_tags JSON NULL,
    completed_count INT NOT NULL DEFAULT 0,
    cancelled_count INT NOT NULL DEFAULT 0,
    no_show_count INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_open_id (open_id),
    KEY idx_user_city_status (city_code, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE activity (
    id BIGINT NOT NULL AUTO_INCREMENT,
    owner_id BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    mode VARCHAR(16) NOT NULL,
    title VARCHAR(80) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    cover_url VARCHAR(500) NULL,
    city_code VARCHAR(20) NULL,
    city_name VARCHAR(40) NULL,
    district VARCHAR(60) NULL,
    address VARCHAR(200) NULL,
    latitude DECIMAL(10, 7) NULL,
    longitude DECIMAL(10, 7) NULL,
    start_at DATETIME(3) NOT NULL,
    end_at DATETIME(3) NOT NULL,
    enroll_deadline DATETIME(3) NOT NULL,
    capacity INT NOT NULL,
    joined_count INT NOT NULL DEFAULT 0,
    fee_fen INT NOT NULL DEFAULT 0,
    deposit_fen INT NOT NULL DEFAULT 0,
    approval_required BIT(1) NOT NULL DEFAULT b'0',
    status VARCHAR(20) NOT NULL,
    tags JSON NULL,
    attributes JSON NULL,
    template_version INT NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_activity_owner FOREIGN KEY (owner_id) REFERENCES user_account (id),
    KEY idx_activity_feed (status, city_code, start_at),
    KEY idx_activity_owner (owner_id, status),
    KEY idx_activity_type_time (type, start_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE enrollment (
    id BIGINT NOT NULL AUTO_INCREMENT,
    activity_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(24) NOT NULL,
    apply_note VARCHAR(200) NULL,
    cancel_reason VARCHAR(200) NULL,
    checked_in_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_enrollment_activity FOREIGN KEY (activity_id) REFERENCES activity (id),
    CONSTRAINT fk_enrollment_user FOREIGN KEY (user_id) REFERENCES user_account (id),
    UNIQUE KEY uk_enrollment_activity_user (activity_id, user_id),
    KEY idx_enrollment_user_status (user_id, status, created_at),
    KEY idx_enrollment_activity_status (activity_id, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE safety_report (
    id BIGINT NOT NULL AUTO_INCREMENT,
    reporter_id BIGINT NOT NULL,
    target_type VARCHAR(24) NOT NULL,
    target_id BIGINT NOT NULL,
    reason_code VARCHAR(32) NOT NULL,
    description VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    handled_by BIGINT NULL,
    handled_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_reporter_user FOREIGN KEY (reporter_id) REFERENCES user_account (id),
    KEY idx_report_status_created (status, created_at),
    KEY idx_report_target (target_type, target_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE outbox_event (
    id BIGINT NOT NULL AUTO_INCREMENT,
    aggregate_type VARCHAR(40) NOT NULL,
    aggregate_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    payload JSON NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    retry_count INT NOT NULL DEFAULT 0,
    available_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    processed_at DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_outbox_idempotency (idempotency_key),
    KEY idx_outbox_dispatch (status, available_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
